### ISSUE TITLE
Loss Criterion failure 

### ISSUE THREAD

**Issue by mattmcc97** [wkentaro/pytorch-fcn#104]
I get the following error when I try and train the network on my own custom dataset with 2 classes:

/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [12,0,0] Assertion t >= 0 && t < n_classes failed.

Traceback (most recent call last):                                              
  File "train_fcn8s_atonce.py", line 118, in <module>                           
    main()
  File "train_fcn8s_atonce.py", line 114, in main
    trainer.train()
  File "../../torchfcn/trainer.py", line 233, in train
    self.train_epoch()
  File "../../torchfcn/trainer.py", line 188, in train_epoch
    self.validate()
  File "../../torchfcn/trainer.py", line 119, in validate
    loss_data = loss.data.item()
RuntimeError: CUDA error: device-side assert triggered

I have kept the dataloader the same apart from the __init__ part.

Could this be due to this part of the code (in __getitem__):

`lbl[lbl == 255] = -1`

As -1 does not fall into the range of 0 and 2?

**Comment by mattmcc97** [comment]
There was some corruption in my dataset, where one of the masks had a value that was not -1 or 0.
