### ISSUE TITLE
How to install the module named 'fcn'?

### ISSUE THREAD

**Issue by RongzhaoZhang** [wkentaro/pytorch-fcn#11]
Now after I ran `python setup.py install`, I got the following error:
```
import torchfcn
Traceback (most recent call last):

  File "<ipython-input-1-c08454750c97>", line 1, in <module>
    import torchfcn

  File "/home/zhang/anaconda2/lib/python2.7/site-packages/torchfcn-0.2-py2.7.egg/torchfcn/__init__.py", line 3, in <module>
    from trainer import Trainer  # NOQA

  File "/home/zhang/anaconda2/lib/python2.7/site-packages/torchfcn-0.2-py2.7.egg/torchfcn/trainer.py", line 6, in <module>
    import fcn

ImportError: No module named fcn****
```

**Comment by wkentaro** [comment]
`pip install -r requirements.txt`
