### ISSUE TITLE
ModuleNotFoundError: No module named 'v1'

### ISSUE THREAD

**Issue by acgtyrant** [wkentaro/pytorch-fcn#18]
```
$ ./train_fcn32s.py
Traceback (most recent call last):
	File "./train_fcn32s.py", line 9, in <module>
		import torchfcn
	File "/home/acgtyrant/Projects/pytorch-fcn/.env/lib/python3.6/site-packages/torchfcn-1.3-py3.6.egg/torchfcn/__init__.py", line 1, in <module>
		from . import datasets  # NOQA
	File "/home/acgtyrant/Projects/pytorch-fcn/.env/lib/python3.6/site-packages/torchfcn-1.3-py3.6.egg/torchfcn/datasets/__init__.py", line 1, in <module>
		from .apc import APC2016V1  # NOQA
	File "/home/acgtyrant/Projects/pytorch-fcn/.env/lib/python3.6/site-packages/torchfcn-1.3-py3.6.egg/torchfcn/datasets/apc/__init__.py", line 1, in <module>
		from v1 import APC2016V1  # NOQA
ModuleNotFoundError: No module named 'v1'
```

**Comment by wkentaro** [comment]
Are you using python3, right?
Currently I've never tried it.
Python3 does not support importing from current directory by default.
so you need to change `from v1 ..` to `from .v1 ...`.

**Comment by acgtyrant** [comment]
Yes, I am using Python 3.

`from .v1 ...` works. Thank you! I will try to make this project be compatible with Python 3.
