### ISSUE TITLE
load_state_dict error

### ISSUE THREAD

**Issue by zheshiyige** [wkentaro/pytorch-fcn#24]
Hi, 
       Recently, I run the examples/voc/train_fcn32s.py, and encountered another error:
       Traceback (most recent call last):
  File "train_fcn32s.py", line 101, in <module>
    main()
  File "train_fcn32s.py", line 55, in main
    vgg16.load_state_dict(torch.load(pth_file))
  File "/home/zheshiyige/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 331, in load_state_dict
    .format(name))
KeyError: 'unexpected key "classifier.1.weight" in state_dict'

I have download the /home/zheshiyige/data/models/torch/vgg16-00b39a1b.pth

Could you tell me how to fix this error?

Thanks and Best Regards,

**Comment by wkentaro** [comment]
pytorch-fcn depends on old torchvision (0.1.7)
Please run `pip install 'torchvision==0.1.7'` (ref: https://github.com/wkentaro/pytorch-fcn/blob/master/requirements.txt#L5)
