### ISSUE TITLE
'Dropout' object has no attribute 'weight'

### ISSUE THREAD

**Issue by zheshiyige** [wkentaro/pytorch-fcn#27]
Hi,
       Thanks so much for your help!    I'm new to pytorch. 
       There is a new error again!
       Traceback (most recent call last):
  File "examples/voc/train_fcn32s.py", line 100, in <module>
    main()
  File "examples/voc/train_fcn32s.py", line 56, in main
    model.copy_params_from_vgg16(vgg16, init_upscore=False)
  File "/home/zheshiyige/Desktop/fully convolutional network/pytorch-fcn-master/torchfcn/models/fcn32s.py", line 117, in copy_params_from_vgg16
    l2.weight.data = l1.weight.data.view(l2.weight.size())
  File "/home/zheshiyige/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 238, in __getattr__
    type(self).__name__, name))
AttributeError: 'Dropout' object has no attribute 'weight'

Thanks and Best Regards,

**Comment by wkentaro** [comment]
I confirmed that this is fixed via https://github.com/wkentaro/pytorch-fcn/commit/0dd12335c8fa8abc5838b033c082f70cb1c485bc
