### ISSUE TITLE
**Training**

### ISSUE THREAD

**Issue by crystal786** [wkentaro/pytorch-fcn#42]
code-block:: bash

  ./train_fcn32s.py config/001.yaml

Running this step, I can see this error, as follows,
Traceback (most recent call last):
  File "./train_fcn32s.py", line 128, in <module>
    main()
  File "/home/xyz/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/xyz/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/xyz/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xyz/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./train_fcn32s.py", line 62, in main
    cfg, out = load_config_file(config_file)
  File "./train_fcn32s.py", line 32, in load_config_file
    name += '_VCS-%s' % git_hash()
  File "./train_fcn32s.py", line 21, in git_hash
    hash = subprocess.check_output(shlex.split(cmd)).strip()
  File "/home/xyz/anaconda2/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/home/xyz/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/xyz/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Wishing for your reply!

**Comment by wkentaro** [comment]
Maybe you don't have `git` command.. https://github.com/wkentaro/pytorch-fcn/blob/master/examples/voc/train_fcn32s.py#L21

**Comment by BarryBA** [comment]
> Maybe you don't have `git` command.. https://github.com/wkentaro/pytorch-fcn/blob/master/examples/voc/train_fcn32s.py#L21

I met the following errors:
    subprocess.CalledProcessError: Command '['git', 'log', '-n', '1', '--pretty=%h']' returned non-zero exit 
    status 128.
Can you tell me how to solve it?
