### ISSUE TITLE
Where can I get the pretrained vgg16 model

### ISSUE THREAD

**Issue by volzkzg** [wkentaro/pytorch-fcn#45]
The error tells me that I don't have the vgg16-from-caffe pretrained model.

bg455@51d9f43122cd:~/projects/pytorch-fcn/examples/voc$ ./train_fcn32s.py  ./config/001.yaml 
Traceback (most recent call last):
  File "./train_fcn32s.py", line 128, in <module>
    main()
  File "/home/bg455/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/bg455/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/bg455/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bg455/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./train_fcn32s.py", line 93, in main
    vgg16 = torchfcn.models.VGG16(pretrained=True)
  File "/usr/local/lib/python2.7/dist-packages/torchfcn-1.5.0-py2.7.egg/torchfcn/models/vgg.py", line 10, in VGG16
    state_dict = torch.load(model_file)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 246, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: '/home/wkentaro/data/models/torch/vgg16-from-caffe.pth'

**Comment by volzkzg** [comment]
It seems that jcjohnson's pretrained model can not be downloaded

**Comment by wkentaro** [comment]
Fixed via ce1cb8867ba215a008ab40c3a3c4502f73b69a0f
