### ISSUE TITLE
excuse me. I have some questions

### ISSUE THREAD

**Issue by Hesansan** [wkentaro/pytorch-fcn#64]
when i try to run this code  
then:

./train_fcn32s.py -g 0 

Traceback (most recent call last):
  File "./train_fcn32s.py", line 164, in <module>
    main()
  File "./train_fcn32s.py", line 129, in main
    vgg16 = torchfcn.models.VGG16(pretrained=True)
  File "/usr/local/lib/python2.7/dist-packages/torchfcn/models/vgg.py", line 13, in VGG16
    model_file = _get_vgg16_pretrained_model()
  File "/usr/local/lib/python2.7/dist-packages/torchfcn/models/vgg.py", line 23, in _get_vgg16_pretrained_model
    md5='aa75b158f4181e7f6230029eb96c1b13',
  File "/usr/local/lib/python2.7/dist-packages/fcn/data.py", line 33, in cached_download
    return gdown.download(url, path, quiet=quiet)
  File "/usr/local/lib/python2.7/dist-packages/gdown/__init__.py", line 58, in download
    res = sess.get(url, stream=True)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=0B9P1L--7Wd2vLTJZMXpIRkVVRFk (Caused by ProxyError('Cannot connect to proxy.', error(104, 'Connection reset by peer')))

 how can i fix it ?  thanks for this code , interesting!

**Comment by wkentaro** [comment]
It seems a network connection problem.
Can you retry to check if it happens again?

**Comment by jxlijunhao** [comment]
请问，h = h[:, :, 19:19 + x.size()[2], 19:19 + x.size()[3]].contiguous()，　中的19是怎么确定出来的

**Comment by wkentaro** [comment]
@jxlijunhao 请看这个 https://github.com/wkentaro/pytorch-fcn/issues/51

**Comment by zhijiew** [comment]
@Hesansan these codes are trying download some pretrained models from google drive, and it can not be visited in China. Maybe you can download it manually and put them in right folder.
