### ISSUE TITLE
TypeError: resize() got an unexpected keyword argument 'anti_aliasing'

### ISSUE THREAD

**Issue by upuil** [wkentaro/pytorch-fcn#72]
I don't konw how to resolve this problem.
```
Traceback (most recent call last):
  File "./examples/voc/train_fcn16s.py", line 111, in <module>
    main()
  File "./examples/voc/train_fcn16s.py", line 107, in main
    trainer.train()
  File "/usr/local/lib/python3.6/dist-packages/torchfcn/trainer.py", line 227, in train
    self.train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/torchfcn/trainer.py", line 182, in train_epoch
    self.validate()
  File "/usr/local/lib/python3.6/dist-packages/torchfcn/trainer.py", line 127, in validate
    lbl_pred=lp, lbl_true=lt, img=img, n_class=n_class)
  File "/usr/local/lib/python3.6/dist-packages/fcn/utils.py", line 365, in visualize_segmentation
    vizs.append(get_tile_image(viz_trues, (1, 3)))
  File "/usr/local/lib/python3.6/dist-packages/fcn/utils.py", line 230, in get_tile_image
    anti_aliasing=True,
TypeError: resize() got an unexpected keyword argument 'anti_aliasing'
```

**Comment by wkentaro** [comment]
I released fcn 6.4.3. So please install it via
```
pip install fcn==6.4.3
```

**Comment by DoffeBupt** [comment]
hello, i have installed fcn6.4.3 but it raises the same error.

**Comment by pazeshun** [comment]
It is solved by https://github.com/wkentaro/pytorch-fcn/issues/73
