### ISSUE TITLE
TypeError: resize() got an unexpected keyword argument 'anti_aliasing'

### ISSUE THREAD

**Issue by DoffeBupt** [wkentaro/pytorch-fcn#73]
the code seems perfect but here raises some error to me.
I have already installed fcn-6.4.3 but it seems doesn't work.
I don't know how to solve that problem.
here is what the terminal shows
what should i do to solve it?

/home/doffe/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[/home/doffe/data/models/pytorch/vgg16_from_caffe.pth] Checking md5 (aa75b158f4181e7f6230029eb96c1b13)
Train:   0%|                                             | 0/12 [00:00<?, ?it/s]/home/doffe/anaconda3/lib/python3.6/site-packages/torchfcn/trainer.py:108: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.                    | 0/8498 [00:00<?, ?it/s]
  data, target = Variable(data, volatile=True), Variable(target)[00:00<?, ?it/s]
/home/doffe/anaconda3/lib/python3.6/site-packages/torchfcn/trainer.py:113: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  loss_data = float(loss.data[0])

Traceback (most recent call last):                                              
  File "./train_fcn32s.py", line 166, in <module>                               
    main()
  File "./train_fcn32s.py", line 162, in main
    trainer.train()
  File "/home/doffe/anaconda3/lib/python3.6/site-packages/torchfcn/trainer.py", line 227, in train
    self.train_epoch()
  File "/home/doffe/anaconda3/lib/python3.6/site-packages/torchfcn/trainer.py", line 182, in train_epoch
    self.validate()
  File "/home/doffe/anaconda3/lib/python3.6/site-packages/torchfcn/trainer.py", line 127, in validate
    lbl_pred=lp, lbl_true=lt, img=img, n_class=n_class)
  File "/home/doffe/anaconda3/lib/python3.6/site-packages/fcn/utils.py", line 372, in visualize_segmentation
    vizs.append(get_tile_image(viz_trues, (1, 3)))
  File "/home/doffe/anaconda3/lib/python3.6/site-packages/fcn/utils.py", line 237, in get_tile_image
    anti_aliasing=True,
  File "/home/doffe/anaconda3/lib/python3.6/site-packages/fcn/utils.py", line 207, in resize
    return skimage.transform.resize(*args, **kwargs)
TypeError: resize() got an unexpected keyword argument 'anti_aliasing'

**Comment by wkentaro** [comment]
Could you try again with `pip install fcn==6.4.4`?

**Comment by DoffeBupt** [comment]
Seems it works! thank you wkentaro!

**Comment by wkentaro** [comment]
Good!

**Comment by upuil** [comment]
It does works! thank you again.

**Comment by wkentaro** [comment]
Sounds great! :+1:
